FROM python:3.13-alpine

WORKDIR /app

# For psycopg2
RUN apk add postgresql-dev gcc python3-dev musl-dev

# Install uv for better package management.
RUN pip install uv

# Install rss_music_api_service dependencies
WORKDIR /app/api_service

COPY api_service/pyproject.toml pyproject.toml
RUN uv sync --no-install-project

# Install rss_music_api_service
COPY api_service .
RUN uv sync

# Expose the port for the backend
EXPOSE 5000

# Configure the environment
ENV FLASK_APP=rss_music_api_service:create_app
ENV FLASK_RUN_HOST=0.0.0.0

# Run the backend
CMD ["uv", "run", "flask", "run"]
