services:
#  frontend:
#    build: ./frontend
#    ports:
#      - "5173:5173"
#    # Keeping node_modules in the container seperate.
#    # Using ./frontend as a volume lets us update files on the fly and have the page
#    # still autoupdate.
#    volumes:
#      - ./frontend:/app
#      - /app/node_modules
#    stdin_open: true
#  backend-api-service:
#    build:
#      context: ./backend/packages/
#      dockerfile: ../docker/local_dev/Dockerfile.api-service
#    ports:
#      - "5000:5000"
#    env_file: ./secrets/backend.env
#    depends_on:
#      database:
#        condition: service_healthy
#      migrations:
#        condition: service_completed_successfully
#    command: python3 -m flask run
  migrations:
    build:
      context: ./backend/packages/
      dockerfile: ../docker/local_dev/Dockerfile.migration-handler
    environment:
      DATABASE_URL: postgresql://postgres:dev-db-password@database:5432
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: dev-db-password
    # Necessary for updating DB schema with Alembic outside Docker.
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
