FROM python:3.13-alpine

WORKDIR /app

# Install dependancies
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

# Copy in the src directory and pyproject.toml
COPY src ./
COPY pyproject.toml ./

# Install the backend as a package
RUN pip3 install .

# Expose the port for the backend
EXPOSE 5000

# Configure the environment
ENV FLASK_APP=rss_music_backend:create_app
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_ENV=production
ENV ALLOWED_ORIGINS=http://willshare.com/*

# Run the backend
CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:5000", "rss_music_backend:wsgi_launch"]
