[project]
name = "rss-music-backend"
version = "0.1.0"
dependencies = [
	"dotenv>=0.9,<1.0",
	"flask>=3.1,<4.0",
	"flask-cors>=6.0,<7.0",
	"requests>=2.32,<3.0",
	"marshmallow>=4.0,<5.0",
	"marshmallow-dataclass>=8.7,<9.0",
	"PyJWT>=2.8.0,<3.0",
]


[project.optional-dependencies]
dev = [
	"pytest",
	"ruff"
]


[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
