"""add_feed_url_to_playlist_tracks

Revision ID: 251e50b93ffd
Revises: 394d642fec21
Create Date: 2026-04-13 15:34:14.875307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "251e50b93ffd"
down_revision: Union[str, Sequence[str], None] = "394d642fec21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("playlist_tracks", sa.Column("feed_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("playlist_tracks", "feed_url")
    # ### end Alembic commands ###
