"""private_profiles_and_playlist_deletes

Revision ID: a531891616b1
Revises: 2ddf7bff99be
Create Date: 2026-04-14 03:33:33.130251

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a531891616b1"
down_revision: Union[str, Sequence[str], None] = "2ddf7bff99be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("playlist_tracks_playlist_id_fkey"), "playlist_tracks", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "playlist_tracks",
        "playlists",
        ["playlist_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("playlists_created_by_user_id_fkey"), "playlists", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "playlists", "users", ["created_by_user_id"], ["id"], ondelete="CASCADE"
    )
    op.alter_column(
        "users",
        "profile_public",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "profile_public",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.drop_constraint(None, "playlists", type_="foreignkey")
    op.create_foreign_key(
        op.f("playlists_created_by_user_id_fkey"),
        "playlists",
        "users",
        ["created_by_user_id"],
        ["id"],
    )
    op.drop_constraint(None, "playlist_tracks", type_="foreignkey")
    op.create_foreign_key(
        op.f("playlist_tracks_playlist_id_fkey"),
        "playlist_tracks",
        "playlists",
        ["playlist_id"],
        ["id"],
    )
    # ### end Alembic commands ###
