services:
  bitcoind:
    build: ./images/bitcoind
    container_name: bitcoind
    environment:
      FUNDED_NODES: lnd-listener,lnd-artist
    healthcheck:
      test: [
        "CMD",
        "bitcoin-cli",
        "-regtest",
        "-rpccookiefile=/mnt/cookie/.cookie",
        "getblockchaininfo"
      ]
      interval: 2s
      timeout: 5s
      retries: 3
    volumes:
      - cookie-vol:/mnt/cookie
      - address-vol:/mnt/addresses:ro
      - channel-signal:/mnt/channels:ro

  lnd-listener:
    container_name: lnd-listener
    build: ./images/lnd 
    depends_on:
      bitcoind:
        condition: service_healthy
    environment:
      BITCOIND_HOST: bitcoind
      BITCOIND_PORT: 18443
      TLS_NAME: lnd-listener
      CHANNEL_PEER_NAME: lnd-artist
      CHANNEL_LIQUIDITY: 10000000
      CONNECT: true
    healthcheck:
      test: [
        "CMD",
        "lncli",
        "--network=regtest",
        "--tlscertpath=/mnt/lnd/tls.cert",
        "--macaroonpath=/mnt/lnd/data/chain/bitcoin/regtest/admin.macaroon",
        "getinfo"
      ]
      interval: 2s
      timeout: 5s
      retries: 3
    volumes:
      - cookie-vol:/mnt/cookie:ro
      - lnd-listener-vol:/mnt/lnd
      - address-vol:/mnt/addresses
      - public-keys:/mnt/pubkeys
      - channel-signal:/mnt/channels
  
  lnd-artist:
    container_name: lnd-artist
    build: ./images/lnd 
    depends_on:
      bitcoind:
        condition: service_healthy
    environment:
      BITCOIND_HOST: bitcoind
      BITCOIND_PORT: 18443
      TLS_NAME: lnd-artist
      CHANNEL_PEER_NAME: lnd-listener
      CHANNEL_LIQUIDITY: 10000000
      CONNECT: false
    healthcheck:
      test: [
        "CMD",
        "lncli",
        "--network=regtest",
        "--tlscertpath=/mnt/lnd/tls.cert",
        "--macaroonpath=/mnt/lnd/data/chain/bitcoin/regtest/admin.macaroon",
        "getinfo"
      ]
      interval: 2s
      timeout: 5s
      retries: 3
    volumes:
      - cookie-vol:/mnt/cookie:ro
      - lnd-artist-vol:/mnt/lnd
      - address-vol:/mnt/addresses
      - public-keys:/mnt/pubkeys
      - channel-signal:/mnt/channels

  nostr-relay:
    image: scsibug/nostr-rs-relay:0.9.0
    container_name: nostr-relay
    ports:
      - 8080:8080
    environment:
      NOSTR_RELAY_PORT: 8080
      NOSTR_RELAY_HOST: 0.0.0.0
      NOSTR_RELAY_PUBLIC: true
    healthcheck:
      test: [
        "CMD",
        "echo",
        ">",
        "/dev/tcp/localhost/8080"
      ]
      interval: 2s
      timeout: 5s
      retries: 3

  lnbits-listener:
    build: ./images/lnbits
    container_name: lnbits-listener
    depends_on:
      lnd-listener:
        condition: service_healthy
      nostr-relay:
        condition: service_healthy
    ports:
      - 4000:5000
    environment:
      LNBITS_BACKEND_WALLET_CLASS: LndWallet
      LND_GRPC_ENDPOINT: lnd-listener
      LND_GRPC_PORT: 10009
      LNBITS_ALLOWED_ORIGINS: http://localhost:4000
      LND_GRPC_CERT: /mnt/lnd/tls.cert
      LND_GRPC_MACAROON: /mnt/lnd/data/chain/bitcoin/regtest/admin.macaroon
      LNBITS_ADMIN_UI: false
      LNBITS_ALLOW_NEW_ACCOUNTS: false
      LNBITS_USER_DEFAULT_EXTENSIONS: nwcprovider
      NWC_RELAY_URL: ws://192.168.1.27:8080
      NWC_SECRET_KEY: AofWMUdY3cpqR++BSLCYKKrQPH1dTQ7zJnGyslyN+do=
      USERNAME: listener 
      PASSWORD: password
      WALLET_NAME: Listener
    volumes:
      - lnd-listener-vol:/mnt/lnd:ro
    extra_hosts:
      - host-lan:${HOST_LAN_IP}

  lnbits-artist:
    build: ./images/lnbits
    container_name: lnbits-artist
    depends_on:
      lnd-artist:
        condition: service_healthy
      nostr-relay:
        condition: service_healthy
    ports:
      - 4001:5000
    environment:
      LNBITS_BACKEND_WALLET_CLASS: LndWallet
      LND_GRPC_ENDPOINT: lnd-artist
      LND_GRPC_PORT: 10009
      LNBITS_ALLOWED_ORIGINS: http://localhost:4001
      LND_GRPC_CERT: /mnt/lnd/tls.cert
      LND_GRPC_MACAROON: /mnt/lnd/data/chain/bitcoin/regtest/admin.macaroon
      LNBITS_ADMIN_UI: false
      LNBITS_ALLOW_NEW_ACCOUNTS: false
      LNBITS_USER_DEFAULT_EXTENSIONS: nwcprovider
      USERNAME: artist
      PASSWORD: password
      WALLET_NAME: Artist
    volumes:
      - lnd-artist-vol:/mnt/lnd:ro
    extra_hosts:
      - host-lan:${HOST_LAN_IP}

volumes:
  lnd-listener-vol: {}
  lnd-artist-vol: {}
  address-vol: {}
  cookie-vol: {}
  public-keys: {}
  channel-signal: {}
