FROM public.ecr.aws/amazonlinux/amazonlinux:2023

# Install general dependencies
RUN dnf install -y python312 findutils zip
RUN python3.12 -m ensurepip --upgrade
RUN pip3 install uv
ENV UV_PYTHON=/usr/bin/python3.12

# Install dependencies for psycogp2
# RUN dnf install -y python3.12-devel postgresql-devel gcc make

WORKDIR /app/build/api_service

COPY ./packages/api_service/pyproject.toml pyproject.toml

# Install backend dependencies (will be cached)
COPY ./packages/common_validators ../common_validators
COPY ./packages/db_service_schemas ../db_service_schemas
COPY ./packages/dynamodb_tables ../dynamodb_tables
COPY ./packages/editable_pages ../editable_pages
RUN uv sync --no-install-project --group lambda

# Install backend package (dependencies cached)
WORKDIR /app/build
COPY ./packages/api_service ./api_service
RUN uv pip install ./api_service[lambda] -t ../

WORKDIR /app
COPY ./packages/api_service/lambda_handler.py lambda_handler.py

# Package dynamic libraries used by some packages.
#COPY copy_lib_requirements.py ./
#RUN mkdir lib
#RUN python3 copy_lib_requirements.py

# Remove unneeded files
RUN rm -rf ./build
RUN rm -rf ./bin
RUN find . -name "__pycache__" -type d -exec rm -rf {} +
#RUN rm copy_lib_requirements.py

CMD ["zip", "/mnt/result/api-service-build.zip", "-r", "."]
