name: Development Deployment

# I've disabled this check because the development deployment has been brought 
# down. Update the development environment in GitHub before re-enabling these
# actions.
#
#on:
#  push:
#    branches:
#      - dev

jobs:
  deploy-dev-stack:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/deploy.yml
    with:
      environment: development
