name: Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/cd-builds.yml
  deploy-stack:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      id-token: write
    needs: build
    container:
      image: python:3.13-alpine
    defaults:
      run:
        working-directory: cdk
    env:
      FRONTEND_BUILD_PATH: "${{ github.workspace }}/builds/dist"
      BACKEND_BUILD_PATH: "${{ github.workspace }}/builds"
      DEPLOY_ENVIRONMENT: "${{ inputs.environment }}"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v5
        with:
          name: frontend-build
          path: builds/dist
      - uses: actions/download-artifact@v5
        with:
          name: backend-build-api-service
          path: builds/
      - uses: actions/download-artifact@v5
        with:
          name: backend-build-db-service
          path: builds/
      - uses: actions/download-artifact@v5
        with:
          name: backend-build-migration-handler
          path: builds/
      - run: apk add nodejs npm
      - run: npm install -g aws-cdk
      - run: python -m pip install --upgrade pip
      - run: python -m pip install -r requirements.txt
      - run: python edit_cdk_json.py
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_DEPLOY_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: cdk deploy --require-approval never
        env:
          # These variables only need to be set in production, they will be ignored in
          # development.
          vars.MPP_DOMAIN_NAME: ${{ vars.MPP_DOMAIN_NAME }}
          vars.MPP_RECORD_NAME: ${{ vars.MPP_RECORD_NAME }}
          vars.MPP_R53_ZONE_ID: ${{ vars.MPP_R53_ZONE_ID }}
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ vars.AWS_POST_DEPLOY_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: python rotate_db_secret.py
